/*
 * NetBeans license header template
 * This comment block is auto-generated by NetBeans IDE
 */
package gui;

/**
 * AboutDialog
 * A modal dialog that displays application information such as
 * version, description, course, and developer details.
 * 
 * @author carlo
 */
public class AboutDialog extends javax.swing.JDialog {

    // Logger instance for logging runtime exceptions and errors
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(AboutDialog.class.getName());

    /**
     * Constructor for AboutDialog
     * 
     * @param parent the parent frame of this dialog
     * @param modal determines whether the dialog is modal
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);   // Call superclass constructor
        initComponents();       // Initialize GUI components
        setLocationRelativeTo(null); // Center dialog on screen
    }

    /**
     * Initializes all Swing components in the dialog.
     * 
     * WARNING:
     * Do NOT modify this method manually.
     * It is auto-generated and maintained by the NetBeans GUI Builder.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Header panel containing the dialog title
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        // Main content panel containing application information
        panelForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        // Action panel containing buttons
        panelActions = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();

        // Set dialog close operation and resizing behavior
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        // Configure header panel background color
        panelHeader.setBackground(new java.awt.Color(31, 60, 136));

        // Configure header label appearance and text
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // Bold font
        jLabel1.setForeground(new java.awt.Color(255, 255, 255)); // White text
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("About MCM");

        // Layout configuration for header panel
        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        // Add header panel to the top of the dialog
        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        // Version label
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><div style=\"width:300px; text-align: center;\">Version 2.0</div></html>");

        // Application name label
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Movie Collection Manager");

        // Course label
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><div style=\"width:300px; text-align: center;\">ICT711 Programming and Algorithms\n</div></html>");

        // Application description label
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html><div style=\"width:300px; text-align: center;\">A Java-based application for managing, searching, sorting,  and evaluating media collections using GUI and TBI interfaces.</div></html>");

        // Developer information label
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html><div style=\"width:300px; text-align: center;\">Developed by: John Carlo Albores</div></html>");

        // Assessment information label
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><div style=\"width:300px; text-align: center;\">Assessment 4 Algorithms and GUI</div></html>");

        // Layout configuration for main content panel
        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        // Add main content panel to the center of the dialog
        getContentPane().add(panelForm, java.awt.BorderLayout.CENTER);

        // Configure OK button appearance and behavior
        btnOk.setBackground(new java.awt.Color(76, 175, 80));
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("Ok");

        // Close dialog when OK button is clicked
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        // Layout configuration for action panel
        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelActionsLayout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addComponent(btnOk)
                .addGap(16, 16, 16))
        );

        // Add action panel to the bottom of the dialog
        getContentPane().add(panelActions, java.awt.BorderLayout.PAGE_END);

        pack(); // Resize dialog to fit components
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler for the OK button
     * Closes the About dialog when clicked
     */
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose(); // Close and release dialog resources
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * Main method (optional)
     * Included by NetBeans template but not required when dialog is launched from parent GUI
     */
    public static void main(String args[]) {

        // Set Nimbus Look and Feel if available
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException |
                 javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Auto-generated dialog launcher code (intentionally commented out)
    }

    // GUI component declarations (auto-generated by NetBeans)
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelHeader;
}
