/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import core.CollectionManager;
import javax.swing.JOptionPane;

/**
 * AddMediaDialog
 * 
 * A modal dialog used to collect user input for adding new media
 * (Movie, Show, or Documentary) into the CollectionManager.
 *
 * @author carlo
 */
public class AddMediaDialog extends javax.swing.JDialog {
    
	// Logger for capturing runtime errors and exceptions
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddMediaDialog.class.getName());
    
    // Reference to the main collection manager (shared application state)
    private final CollectionManager collection;

    /**
     * Creates new form AddMediaDialog with parameters:
     * parent = the parent frame
     * modal = determines whether the dialog is modal
     * collection = the collection manager used to store media
     */
    public AddMediaDialog(java.awt.Frame parent, boolean modal, CollectionManager collection) {
        super(parent, modal); // Call JDialog constructor
        this.collection = collection; // Store collection reference
        initComponents(); // Initialize Swing components
        initRatingSpinner(); // Configure rating spinner
        
        // Hide all type-specific panels by default
        panelMovieFields.setVisible(false);
        panelShowFields.setVisible(false);
        panelDocFields.setVisible(false);

        // Initialize logic for handling media type selection
        initTypeHandling(); 
        
        // Set dialog window title
        setTitle("Add Media");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	// Header panel and labels
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        
        // Main form panel and common fields
        panelForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spnRating = new javax.swing.JSpinner();
        
        // Documentary-specific fields
        panelDocFields = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        
        // Show-specific fields
        panelShowFields = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSeasons = new javax.swing.JTextField();
        txtEpisodes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        
        
        // Movie-specific fields
        panelMovieFields = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbMovieType = new javax.swing.JComboBox<>();
        
        // Action buttons panel
        panelActions = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        
        // Configure dialog behavior
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        
        // Header styling
        panelHeader.setBackground(new java.awt.Color(31, 60, 136));

        // Header title label
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Media");
        
        // Header subtitle label
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Required fields are marked with an asterisk");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        
        // Add header panel to the top of the dialog
        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);
        
        // Labels and input field configuration
        jLabel2.setText("* Title:");

        txtTitle.setCaretColor(new java.awt.Color(31, 60, 136));
        txtTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("* Type:");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Media Type", "Movie", "Show", "Documentary" }));

        jLabel4.setText("* Genre:");

        txtGenre.setCaretColor(new java.awt.Color(31, 60, 136));

        jLabel5.setText("* Year:");

        txtYear.setCaretColor(new java.awt.Color(31, 60, 136));

        jLabel6.setText("* Rating:");

        jLabel12.setText("* Subject/Topic:");

        txtSubject.setCaretColor(new java.awt.Color(31, 60, 136));

        javax.swing.GroupLayout panelDocFieldsLayout = new javax.swing.GroupLayout(panelDocFields);
        panelDocFields.setLayout(panelDocFieldsLayout);
        panelDocFieldsLayout.setHorizontalGroup(
            panelDocFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocFieldsLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panelDocFieldsLayout.setVerticalGroup(
            panelDocFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocFieldsLayout.createSequentialGroup()
                .addGroup(panelDocFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        // Show fields labels
        jLabel10.setText("* Number of Seasons:");

        txtSeasons.setCaretColor(new java.awt.Color(31, 60, 136));

        txtEpisodes.setCaretColor(new java.awt.Color(31, 60, 136));

        jLabel11.setText("* Number of Episodes:");

        javax.swing.GroupLayout panelShowFieldsLayout = new javax.swing.GroupLayout(panelShowFields);
        panelShowFields.setLayout(panelShowFieldsLayout);
        panelShowFieldsLayout.setHorizontalGroup(
            panelShowFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowFieldsLayout.createSequentialGroup()
                .addGroup(panelShowFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelShowFieldsLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEpisodes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelShowFieldsLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSeasons, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panelShowFieldsLayout.setVerticalGroup(
            panelShowFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowFieldsLayout.createSequentialGroup()
                .addGroup(panelShowFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeasons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShowFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEpisodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        // Movie type label and dropdown
        jLabel8.setText("* Movie Type:");

        cmbMovieType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Movie Type", "Indie", "Blockbuster", "Short", "Classic" }));

        javax.swing.GroupLayout panelMovieFieldsLayout = new javax.swing.GroupLayout(panelMovieFields);
        panelMovieFields.setLayout(panelMovieFieldsLayout);
        panelMovieFieldsLayout.setHorizontalGroup(
            panelMovieFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovieFieldsLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMovieType, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );
        panelMovieFieldsLayout.setVerticalGroup(
            panelMovieFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovieFieldsLayout.createSequentialGroup()
                .addGroup(panelMovieFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMovieType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDocFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelMovieFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                            .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spnRating, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                            .addGap(51, 51, 51)))
                    .addComponent(panelShowFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMovieFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShowFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDocFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        
        // Add main form panel to the dialog
        getContentPane().add(panelForm, java.awt.BorderLayout.CENTER);
        
        // Save button configuration
        btnSave.setBackground(new java.awt.Color(76, 175, 80));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        
        // Cancel button configuration
        btnCancel.setBackground(new java.awt.Color(244, 66, 53));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(16, 16, 16))
        );
        
        // Add action panel to the bottom of the dialog
        getContentPane().add(panelActions, java.awt.BorderLayout.PAGE_END);
	        
	     // Resize dialog to fit components
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    // Basic validation
        if (cmbType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(
                this,
                "Please select a media type.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        // Retrieve and sanitize common input fields
        String title = txtTitle.getText().trim();
        String genre = txtGenre.getText().trim();
        int year = Integer.parseInt(txtYear.getText().trim());
        double rating = (double) spnRating.getValue();

        
        // Validate required common fields
        if (title.isEmpty() || genre.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Title and Genre are required.",
                "Validation Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Media-type specific logic
        String type = cmbType.getSelectedItem().toString();

        try {
            switch (type) {
            
            	// Movie creation logic
                case "Movie" -> {
                    String movieType = cmbMovieType.getSelectedItem().toString();
                    if (movieType.equals("Select movie type")) {
                        throw new IllegalArgumentException("Please select a movie type.");
                    }
                    collection.addMovie(title, genre, year, rating, movieType);
                }
                
                // TV Show creation logic
                case "Show" -> {
                    int seasons = Integer.parseInt(txtSeasons.getText().trim());
                    int episodes = Integer.parseInt(txtEpisodes.getText().trim());
                    collection.addShow(title, genre, year, rating, seasons, episodes);
                }

                // Documentary creation logic
                case "Documentary" -> {
                    String subject = txtSubject.getText().trim();
                    if (subject.isEmpty()) {
                        throw new IllegalArgumentException("Subject is required.");
                    }
                    collection.addDocumentary(title, genre, year, rating, subject);
                }
            }
            
            // Success message
            JOptionPane.showMessageDialog(
                this,
                "Media added successfully.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE
            );

            dispose(); // close dialog

        } catch (Exception ex) {
        	// Display validation or parsing errors
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Input Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose(); // close dialog
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void initRatingSpinner() {
        javax.swing.SpinnerNumberModel ratingModel =
                new javax.swing.SpinnerNumberModel(5.0, 0.0, 10.0, 0.1);

        spnRating.setModel(ratingModel);

        javax.swing.JSpinner.NumberEditor editor =
                new javax.swing.JSpinner.NumberEditor(spnRating, "0.0");
        spnRating.setEditor(editor);
    }
    
    private void initTypeHandling() {
        cmbType.addActionListener(e -> updateTypeFields());
        updateTypeFields(); // ensure correct state on open
    }
    
    private void updateTypeFields() {
        String type = cmbType.getSelectedItem().toString();

        panelMovieFields.setVisible(false);
        panelShowFields.setVisible(false);
        panelDocFields.setVisible(false);

        switch (type) {
            case "Movie" -> panelMovieFields.setVisible(true);
            case "Show" -> panelShowFields.setVisible(true);
            case "Documentary" -> panelDocFields.setVisible(true);
            default -> {
                // "Select media type" → show nothing
            }
        }

        panelForm.revalidate();
        panelForm.repaint();
    }
    
    private boolean validateInputs() {

        // ===== COMMON FIELDS =====
        if (txtTitle.getText().trim().isEmpty()) {
            showError("Title cannot be empty.");
            return false;
        }

        if (txtGenre.getText().trim().isEmpty()) {
            showError("Genre cannot be empty.");
            return false;
        }

        // Year validation (textfield)
        int year;
        try {
            year = Integer.parseInt(txtYear.getText().trim());
            if (year < 1900 || year > 2100) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            showError("Please enter a valid year between 1900 and 2100.");
            return false;
        }

        // Media type validation
        if (cmbType.getSelectedIndex() == 0) {
            showError("Please select a media type.");
            return false;
        }

        String type = cmbType.getSelectedItem().toString();

        // ===== TYPE-SPECIFIC VALIDATION =====
        switch (type) {
            case "Movie" -> {

                if (!panelMovieFields.isVisible()) {
                    return true; // safety guard (should never happen)
                }

                if (cmbMovieType.getSelectedIndex() == 0) {
                    showError("Please select a movie type.");
                    return false;
                }
            }


            case "Show" -> {
                try {
                    int seasons = Integer.parseInt(txtSeasons.getText().trim());
                    int episodes = Integer.parseInt(txtEpisodes.getText().trim());

                    if (seasons <= 0 || episodes <= 0) {
                        throw new NumberFormatException();
                    }
                } catch (NumberFormatException e) {
                    showError("Seasons and Episodes must be positive whole numbers.");
                    return false;
                }
            }

            case "Documentary" -> {
                if (txtSubject.getText().trim().isEmpty()) {
                    showError("Documentary subject cannot be empty.");
                    return false;
                }
            }
        }

        return true; // ✅ all validations passed
    }

    private void showError(String message) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            message,
            "Invalid Input",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddMediaDialog dialog = new AddMediaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbMovieType;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelDocFields;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMovieFields;
    private javax.swing.JPanel panelShowFields;
    private javax.swing.JSpinner spnRating;
    private javax.swing.JTextField txtEpisodes;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtSeasons;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
